steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "deploy/Dockerfile", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/demo-agent/demo-agent-backend:latest", "."]
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/demo-agent/demo-agent-backend:latest"
