steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "deploy/Dockerfile", "-t", "gcr.io/$PROJECT_ID/demo-agent-backend:latest", "."]
images:
  - "gcr.io/$PROJECT_ID/demo-agent-backend:latest"
